<h1 align='center'>House Price Predictor</h1>

In [195]:
!pip install scikit-learn --upgrade --quiet

In [196]:
!pip install opendatasets --upgrade --quiet

In [197]:
import opendatasets as od

You should have a kaggle account and api key to download data set. 
you have to accept rules for this data set on kaggle before downloading

In [198]:
url='https://www.kaggle.com/c/house-prices-advanced-regression-techniques'

In [199]:
od.download(url)

Skipping, found downloaded files in "./house-prices-advanced-regression-techniques" (use force=True to force download)

In [200]:
import os
data='./house-prices-advanced-regression-techniques'

In [201]:
os.listdir(data)

['sample_submission.csv', 'train.csv', 'data_description.txt', 'test.csv']

In [202]:
Sample=data+'/sample_submission.csv'
Test=data+'/test.csv'
Train=data+'/train.csv'
descp=data+'/data_description.txt'

In [203]:
!pip install pandas --upgrade --quiet

In [204]:
import pandas as pd
Test_df=pd.read_csv(Test)
Train_df=pd.read_csv(Train)
Sample_df=pd.read_csv(Sample)

In [205]:
pd.set_option('display.max_columns', None)
Train_df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,5,1999,2000,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,PConc,Gd,TA,No,Unf,0,Unf,0,953,953,GasA,Ex,Y,SBrkr,953,694,0,1647,0,0,2,1,3,1,TA,7,Typ,1,TA,Attchd,1999.0,RFn,2,460,TA,TA,Y,0,40,0,0,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,6,6,1978,1988,Gable,CompShg,Plywood,Plywood,Stone,119.0,TA,TA,CBlock,Gd,TA,No,ALQ,790,Rec,163,589,1542,GasA,TA,Y,SBrkr,2073,0,0,2073,1,0,2,0,3,1,TA,7,Min1,2,TA,Attchd,1978.0,Unf,2,500,TA,TA,Y,349,0,0,0,0,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,9,1941,2006,Gable,CompShg,CemntBd,CmentBd,NaN,0.0,Ex,Gd,Stone,TA,Gd,No,GLQ,275,Unf,0,877,1152,GasA,Ex,Y,SBrkr,1188,1152,0,2340,0,0,2,0,4,1,Gd,9,Typ,2,Gd,Attchd,1941.0,RFn,1,252,TA,TA,Y,0,60,0,0,0,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,5,6,1950,1996,Hip,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,TA,TA,Mn,GLQ,49,Rec,1029,0,1078,GasA,Gd,Y,FuseA,1078,0,0,1078,1,0,1,0,2,1,Gd,5,Typ,0,NaN,Attchd,1950.0,Unf,1,240,TA,TA,Y,366,0,112,0,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1Story,5,6,1965,1965,Gable,CompShg,HdBoard,HdBoard,NaN,0.0,Gd,TA,CBlock,TA,TA,No,BLQ,830,LwQ,290,136,1256,GasA,Gd,Y,SBrkr,1256,0,0,1256,1,0,1,1,3,1,TA,6,Typ,0,NaN,Attchd,1965.0,Fin,1,276,TA,TA,Y,736,68,0,0,0,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [206]:
Train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   str
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   str
 6   Alley          91 non-null     str
 7   LotShape       1460 non-null   str
 8   LandContour    1460 non-null   str
 9   Utilities      1460 non-null   str
 10  LotConfig      1460 non-null   str
 11  LandSlope      1460 non-null   str
 12  Neighborhood   1460 non-null   str
 13  Condition1     1460 non-null   str
 14  Condition2     1460 non-null   str
 15  BldgType       1460 non-null   str
 16  HouseStyle     1460 non-null   str
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   str
 22  RoofMatl       1460 non-null   str
 23  Exterior1st    1460 non-null   str
 24  Exterior2nd    1460 non-null   str
 25  MasVnrType     588 non-null    str
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   str
 28  ExterCond      1460 non-null   str
 29  Foundation     1460 non-null   str
 30  BsmtQual       1423 non-null   str
 31  BsmtCond       1423 non-null   str
 32  BsmtExposure   1422 non-null   str
 33  BsmtFinType1   1423 non-null   str
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   str
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   str
 40  HeatingQC      1460 non-null   str
 41  CentralAir     1460 non-null   str
 42  Electrical     1459 non-null   str
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   str
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   str
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    str
 58  GarageType     1379 non-null   str
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   str
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   str
 64  GarageCond     1379 non-null   str
 65  PavedDrive     1460 non-null   str
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      str
 73  Fence          281 non-null    str
 74  MiscFeature    54 non-null     str
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   str
 79  SaleCondition  1460 non-null   str
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), str(43)
memory usage: 1.1 MB

According to data rules Na dosent mean data missing it means the feature is not present in that house so replacing Nan with none

In [207]:
no_feature_cols = [
    'PoolQC', 'MiscFeature', 'Alley', 'Fence', 'FireplaceQu',
    'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond',
    'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2','MasVnrType'
]

Train_df[no_feature_cols] = Train_df[no_feature_cols].fillna('None')
Train_df['MasVnrArea'] = Train_df['MasVnrArea'].fillna(0)
Test_df[no_feature_cols] = Train_df[no_feature_cols].fillna('None')
Test_df['MasVnrArea'] = Train_df['MasVnrArea'].fillna(0)

In [208]:
Train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   str
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   str
 6   Alley          1460 non-null   str
 7   LotShape       1460 non-null   str
 8   LandContour    1460 non-null   str
 9   Utilities      1460 non-null   str
 10  LotConfig      1460 non-null   str
 11  LandSlope      1460 non-null   str
 12  Neighborhood   1460 non-null   str
 13  Condition1     1460 non-null   str
 14  Condition2     1460 non-null   str
 15  BldgType       1460 non-null   str
 16  HouseStyle     1460 non-null   str
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   str
 22  RoofMatl       1460 non-null   str
 23  Exterior1st    1460 non-null   str
 24  Exterior2nd    1460 non-null   str
 25  MasVnrType     1460 non-null   str
 26  MasVnrArea     1460 non-null   float64
 27  ExterQual      1460 non-null   str
 28  ExterCond      1460 non-null   str
 29  Foundation     1460 non-null   str
 30  BsmtQual       1460 non-null   str
 31  BsmtCond       1460 non-null   str
 32  BsmtExposure   1460 non-null   str
 33  BsmtFinType1   1460 non-null   str
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1460 non-null   str
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   str
 40  HeatingQC      1460 non-null   str
 41  CentralAir     1460 non-null   str
 42  Electrical     1459 non-null   str
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   str
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   str
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    1460 non-null   str
 58  GarageType     1460 non-null   str
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1460 non-null   str
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1460 non-null   str
 64  GarageCond     1460 non-null   str
 65  PavedDrive     1460 non-null   str
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         1460 non-null   str
 73  Fence          1460 non-null   str
 74  MiscFeature    1460 non-null   str
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   str
 79  SaleCondition  1460 non-null   str
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), str(43)
memory usage: 1.1 MB

Still have some null because looking at the data those values are actualy missing like Electrical and LotFrontage

In [209]:
Train_df['GarageYrBlt']=Train_df['GarageYrBlt'].fillna('YearBuilt')
Test_df['GarageYrBlt']=Test_df['GarageYrBlt'].fillna('YearBuilt')

In [210]:
from sklearn.model_selection import train_test_split
Train_Split_df, Val_df=train_test_split(Train_df, test_size=0.2, random_state=40)

In [211]:
Target_col=Train_Split_df['SalePrice']
Input_col=Train_Split_df.drop(columns=['Id', 'SalePrice', 'Utilities'])
Val_Target=Val_df['SalePrice']
Val_df_Input=Val_df.drop(columns=['Id', 'SalePrice', 'Utilities'])
Test_df_input=Test_df.drop(columns=['Id', 'Utilities'])

In [212]:
null_counts = Input_col.isnull().sum()
null_summary = null_counts[null_counts > 0].sort_values(ascending=False)
print(null_summary)

LotFrontage    212
Electrical       1
dtype: int64

In [213]:
from sklearn.impute import SimpleImputer

Imputer_median=SimpleImputer(strategy='median')
Imputer_frq=SimpleImputer(strategy='most_frequent')
Imputer_median.fit(Input_col[['LotFrontage']])
Imputer_frq.fit(Input_col[['Electrical']])

SimpleImputer(strategy='most_frequent')

In [214]:
Input_col['LotFrontage']=Imputer_median.transform(Input_col[['LotFrontage']]).ravel()
Input_col['Electrical']=Imputer_frq.transform(Input_col[['Electrical']]).ravel()
Val_df_Input['LotFrontage']=Imputer_median.transform(Val_df_Input[['LotFrontage']]).ravel()
Val_df_Input['Electrical']=Imputer_frq.transform(Val_df_Input[['Electrical']]).ravel()
Test_df_input['LotFrontage']=Imputer_median.transform(Test_df_input[['LotFrontage']]).ravel()
Test_df_input['Electrical']=Imputer_frq.transform(Test_df_input[['Electrical']]).ravel()

Encodding catagorical data

In [215]:
Input_col['GarageYrBlt'] = pd.to_numeric(Input_col['GarageYrBlt'], errors='coerce')
Input_col['GarageYrBlt'] = Input_col['GarageYrBlt'].fillna(0)
Val_df_Input['GarageYrBlt'] = pd.to_numeric(Input_col['GarageYrBlt'], errors='coerce')
Val_df_Input['GarageYrBlt'] = Input_col['GarageYrBlt'].fillna(0)
Test_df_input['GarageYrBlt'] = pd.to_numeric(Input_col['GarageYrBlt'], errors='coerce')
Test_df_input['GarageYrBlt'] = Input_col['GarageYrBlt'].fillna(0)

In [216]:
numeric_colls=Input_col.select_dtypes(include=['number']).columns.tolist()
categorical_cols = Input_col.select_dtypes(exclude=['number']).columns.tolist()

In [217]:
Input_col

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
609,20,RL,61.0,7943,Pave,None,Reg,Lvl,Inside,Gtl,Sawyer,Feedr,Norm,1Fam,1Story,4,5,1961,1961,Gable,CompShg,VinylSd,VinylSd,BrkCmn,192.0,TA,Fa,CBlock,TA,TA,Mn,Rec,903,Unf,0,126,1029,GasA,Gd,Y,SBrkr,1029,0,0,1029,1,0,1,0,3,1,TA,5,Typ,0,None,Attchd,1961.0,Unf,1,261,TA,TA,Y,64,0,39,0,0,0,None,None,None,0,4,2007,WD,Normal
1361,20,RL,124.0,16158,Pave,None,IR1,Low,Inside,Mod,StoneBr,Norm,Norm,1Fam,1Story,7,5,2005,2005,Hip,CompShg,VinylSd,VinylSd,Stone,16.0,Gd,TA,PConc,Ex,TA,Av,ALQ,1274,Unf,0,256,1530,GasA,Ex,Y,SBrkr,1530,0,0,1530,1,0,2,0,3,1,Gd,7,Typ,1,Gd,Attchd,2005.0,Fin,2,430,TA,TA,Y,168,36,0,0,0,0,None,None,None,0,6,2009,WD,Normal
1076,50,RL,60.0,10800,Pave,Grvl,Reg,Lvl,Inside,Gtl,OldTown,Norm,Norm,1Fam,1.5Fin,5,8,1936,1989,Gable,CompShg,Wd Sdng,Wd Sdng,None,0.0,TA,TA,CBlock,Fa,TA,No,ALQ,626,Unf,0,170,796,GasA,Gd,Y,SBrkr,1096,370,0,1466,0,1,2,0,3,1,Gd,7,Min1,1,TA,Attchd,1950.0,Unf,2,566,TA,TA,Y,436,21,0,0,0,0,None,None,Shed,500,4,2006,WD,Normal
1138,20,RL,70.0,9819,Pave,None,IR1,Lvl,Inside,Mod,Mitchel,Norm,Norm,1Fam,1Story,6,5,1977,1977,Gable,CompShg,Plywood,ImStucc,None,0.0,TA,TA,PConc,TA,TA,Gd,ALQ,1567,Unf,0,0,1567,GasA,TA,Y,SBrkr,1567,0,0,1567,1,0,2,0,2,1,Gd,5,Typ,2,TA,Attchd,1977.0,RFn,2,714,TA,TA,Y,264,32,0,0,0,0,None,None,None,0,5,2009,WD,Normal
1159,60,RL,76.0,9120,Pave,None,Reg,Lvl,Inside,Gtl,NWAmes,Norm,Norm,1Fam,2Story,6,6,1974,1974,Hip,CompShg,HdBoard,HdBoard,BrkFace,270.0,Gd,TA,CBlock,TA,TA,No,ALQ,442,Unf,0,459,901,GasA,TA,Y,SBrkr,943,933,0,1876,0,0,2,1,4,1,Gd,8,Typ,1,TA,Attchd,1974.0,RFn,2,540,Gd,TA,Y,0,69,0,0,0,0,None,None,None,0,7,2008,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1016,20,RL,73.0,11883,Pave,None,Reg,Lvl,Inside,Gtl,CollgCr,Norm,Norm,1Fam,1Story,7,5,1996,1996,Hip,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,Gd,GLQ,690,Unf,0,814,1504,GasA,Ex,Y,SBrkr,1504,0,0,1504,1,0,2,0,3,1,Gd,6,Typ,1,TA,Attchd,1996.0,Fin,2,478,TA,TA,Y,115,66,0,0,0,0,None,None,None,0,6,2009,WD,Normal
165,190,RL,62.0,10106,Pave,None,Reg,Lvl,Inside,Gtl,Edwards,Norm,Norm,2fmCon,1.5Fin,5,7,1940,1999,Gable,CompShg,Wd Sdng,Wd Sdng,None,0.0,TA,Gd,BrkTil,TA,TA,No,ALQ,351,Rec,181,112,644,GasA,Gd,Y,SBrkr,808,547,0,1355,1,0,2,0,4,2,TA,6,Typ,0,None,None,0.0,None,0,0,None,None,Y,140,0,0,0,0,0,None,None,None,0,9,2008,WD,Normal
7,60,RL,70.0,10382,Pave,None,IR1,Lvl,Corner,Gtl,NWAmes,PosN,Norm,1Fam,2Story,7,6,1973,1973,Gable,CompShg,HdBoard,HdBoard,Stone,240.0,TA,TA,CBlock,Gd,TA,Mn,ALQ,859,BLQ,32,216,1107,GasA,Ex,Y,SBrkr,1107,983,0,2090,1,0,2,1,3,1,TA,7,Typ,2,TA,Attchd,1973.0,RFn,2,484,TA,TA,Y,235,204,228,0,0,0,None,None,Shed,350,11,2009,WD,Normal
219,120,RL,43.0,3010,Pave,None,Reg,Lvl,Inside,Gtl,Blmngtn,Norm,Norm,TwnhsE,1Story,7,5,2005,2006,Gable,CompShg,VinylSd,VinylSd,BrkFace,16.0,Gd,TA,PConc,Gd,TA,Av,GLQ,16,Unf,0,1232,1248,GasA,Ex,Y,SBrkr,1248,0,0,1248,0,0,2,0,2,1,Gd,5,Typ,0,None,Attchd,2005.0,Fin,2,438,TA,TA,Y,108,0,0,0,0,0,None,None,None,0,3,2006,New,Partial
1350,90,RL,91.0,11643,Pave,None,Reg,Lvl,Inside,Gtl,NAmes,Artery,Norm,Duplex,2Story,5,5,1969,1969,Gable,CompShg,MetalSd,MetalSd,BrkFace,368.0,TA,TA,CBlock,TA,TA,No,LwQ,500,Unf,0,748,1248,GasA,TA,Y,SBrkr,1338,1296,0,2634,1,1,2,2,6,2,TA,12,Typ,0,None,Detchd,1969.0,Unf,4,968,TA,TA,Y,0,0,0,0,0,0,None,None,None,0,8,2009,WD,Normal

In [218]:
from sklearn.preprocessing import StandardScaler
Scaler=StandardScaler()
Scaler.fit(Input_col[numeric_colls])
Input_col[numeric_colls]=Scaler.transform(Input_col[numeric_colls])
Val_df_Input[numeric_colls]=Scaler.transform(Val_df_Input[numeric_colls])
Test_df_input[numeric_colls]=Scaler.transform(Test_df_input[numeric_colls])

In [219]:
Input_col

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
609,-0.871658,RL,-0.412306,-0.252659,Pave,None,Reg,Lvl,Inside,Gtl,Sawyer,Feedr,Norm,1Fam,1Story,-1.507104,-0.504499,-0.358283,-1.174415,Gable,CompShg,VinylSd,VinylSd,BrkCmn,0.490392,TA,Fa,CBlock,TA,TA,Mn,Rec,0.979082,Unf,-0.287698,-0.987686,-0.067266,GasA,Gd,Y,SBrkr,-0.349456,-0.788740,-0.123494,-0.917962,1.086130,-0.243189,-1.028393,-0.766158,0.174249,-0.214926,TA,-0.927155,Typ,-0.965196,None,Attchd,0.207936,Unf,-1.010712,-0.976445,TA,TA,Y,-0.230072,-0.715402,0.286313,-0.117729,-0.257976,-0.071069,None,None,None,-0.086176,-0.878757,-0.614908,WD,Normal
1361,-0.871658,RL,2.391941,0.498726,Pave,None,IR1,Low,Inside,Mod,StoneBr,Norm,Norm,1Fam,1Story,0.643096,-0.504499,1.110048,0.968512,Hip,CompShg,VinylSd,VinylSd,Stone,-0.479820,Gd,TA,PConc,Ex,TA,Av,ALQ,1.777277,Unf,-0.287698,-0.693965,1.049542,GasA,Ex,Y,SBrkr,0.934911,-0.788740,-0.123494,0.031749,1.086130,-0.243189,0.799861,-0.766158,0.174249,-0.214926,Gd,0.292346,Typ,0.568612,Gd,Attchd,0.303436,Fin,0.323199,-0.189397,TA,TA,Y,0.590748,-0.161216,-0.352538,-0.117729,-0.257976,-0.071069,None,None,None,-0.086176,-0.131478,0.890778,WD,Normal
1076,-0.165219,RL,-0.456818,0.008656,Pave,Grvl,Reg,Lvl,Inside,Gtl,OldTown,Norm,Norm,1Fam,1.5Fin,-0.790370,2.223533,-1.192562,0.189266,Gable,CompShg,Wd Sdng,Wd Sdng,None,-0.568021,TA,TA,CBlock,Fa,TA,No,ALQ,0.383125,Unf,-0.287698,-0.888273,-0.586660,GasA,Gd,Y,SBrkr,-0.177694,0.065157,-0.123494,-0.089572,-0.838908,3.873394,0.799861,-0.766158,0.174249,-0.214926,Gd,0.292346,Min1,0.568612,TA,Attchd,0.184062,Unf,0.323199,0.443966,TA,TA,Y,2.705938,-0.392127,-0.352538,-0.117729,-0.257976,-0.071069,None,None,Shed,0.831121,-0.878757,-1.367751,WD,Normal
1138,-0.871658,RL,-0.011700,-0.081071,Pave,None,IR1,Lvl,Inside,Mod,Mitchel,Norm,Norm,1Fam,1Story,-0.073637,-0.504499,0.175656,-0.395169,Gable,CompShg,Plywood,ImStucc,None,-0.568021,TA,TA,PConc,TA,TA,Gd,ALQ,2.407657,Unf,-0.287698,-1.272370,1.132020,GasA,TA,Y,SBrkr,1.029764,-0.788740,-0.123494,0.101887,1.086130,-0.243189,0.799861,-0.766158,-1.059220,-0.214926,Gd,-0.927155,Typ,2.102421,TA,Attchd,0.242663,RFn,0.323199,1.133215,TA,TA,Y,1.348428,-0.222792,-0.352538,-0.117729,-0.257976,-0.071069,None,None,None,-0.086176,-0.505117,0.890778,WD,Normal
1159,0.070261,RL,0.255372,-0.145005,Pave,None,Reg,Lvl,Inside,Gtl,NWAmes,Norm,Norm,1Fam,2Story,-0.073637,0.404845,0.075542,-0.541277,Hip,CompShg,HdBoard,HdBoard,BrkFace,0.920372,Gd,TA,CBlock,TA,TA,No,ALQ,-0.012745,Unf,-0.287698,-0.235308,-0.352598,GasA,TA,Y,SBrkr,-0.569926,1.364464,-0.123494,0.687636,-0.838908,-0.243189,0.799861,1.209277,1.407718,-0.214926,Gd,0.902097,Typ,0.568612,TA,Attchd,0.236152,RFn,0.323199,0.322882,Gd,TA,Y,-0.735192,0.346788,-0.352538,-0.117729,-0.257976,-0.071069,None,None,None,-0.086176,0.242162,0.137935,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1016,-0.871658,RL,0.121836,0.107713,Pave,None,Reg,Lvl,Inside,Gtl,CollgCr,Norm,Norm,1Fam,1Story,0.643096,-0.504499,0.809708,0.530186,Hip,CompShg,VinylSd,VinylSd,BrkFace,0.512442,Gd,TA,PConc,Gd,TA,Gd,GLQ,0.520819,Unf,-0.287698,0.566777,0.991584,GasA,Ex,Y,SBrkr,0.868257,-0.788740,-0.123494,-0.017538,1.086130,-0.243189,0.799861,-0.766158,0.174249,-0.214926,Gd,-0.317405,Typ,0.568612,TA,Attchd,0.283902,Fin,0.323199,0.034143,TA,TA,Y,0.172446,0.300606,-0.352538,-0.117729,-0.257976,-0.071069,None,None,None,-0.086176,-0.131478,0.890778,WD,Normal
165,3.131496,RL,-0.367794,-0.054820,Pave,None,Reg,Lvl,Inside,Gtl,Edwards,Norm,Norm,2fmCon,1.5Fin,-0.790370,1.314189,-1.059077,0.676294,Gable,CompShg,Wd Sdng,Wd Sdng,None,-0.568021,TA,Gd,BrkTil,TA,TA,No,ALQ,-0.208528,Rec,0.794789,-1.019318,-0.925491,GasA,Gd,Y,SBrkr,-0.916013,0.473642,-0.123494,-0.299987,1.086130,-0.243189,0.799861,-0.766158,1.407718,4.189173,TA,-0.317405,Typ,-0.965196,None,None,-4.048289,None,-2.344623,-2.191944,None,None,Y,0.369758,-0.715402,-0.352538,-0.117729,-0.257976,-0.071069,None,None,None,-0.086176,0.989441,0.137935,WD,Normal
7,0.070261,RL,-0.011700,-0.029576,Pave,None,IR1,Lvl,Corner,Gtl,NWAmes,PosN,Norm,1Fam,2Story,0.643096,0.404845,0.042171,-0.589980,Gable,CompShg,HdBoard,HdBoard,Stone,0.754995,TA,TA,CBlock,Gd,TA,Mn,ALQ,0.884417,BLQ,-0.096319,-0.784341,0.106608,GasA,Ex,Y,SBrkr,-0.149495,1.479855,-0.123494,1.093301,1.086130,-0.243189,0.799861,1.209277,0.174249,-0.214926,TA,0.292346,Typ,2.102421,TA,Attchd,0.233982,RFn,0.323199,0.062085,TA,TA,Y,1.119545,2.424987,3.382284,-0.117729,-0.257976,-0.071069,None,None,Shed,0.555932,1.736720,0.890778,WD,Normal
219,1.483139,RL,-1.213520,-0.703856,Pave,None,Reg,Lvl,Inside,Gtl,Blmngtn,Norm,Norm,TwnhsE,1Story,0.643096,-0.504499,1.110048,1.017214,Gable,CompShg,VinylSd,VinylSd,BrkFace,-0.479820,Gd,TA,PConc,Gd,TA,Av,GLQ,-0.929270,Unf,-0.287698,1.511204,0.420919,GasA,Ex,Y,SBrkr,0.211974,-0.788740,-0.123494,-0.502819,-0.838908,-0.243189,0.799861,-0.766158,-1.059220,-0.214926,Gd,-0.927155,Typ,-0.965196,None,Attchd,0.303436,Fin,0.323199,-0.152141,TA,TA,Y,0.117198,-0.715402,-0.352538,-0.117729,-0.257976,-0.071069,None,None,None,-0.086176,-1.252396,-1.367751,New,Partial
1350,0.776700,RL,0.923049,0.085761,Pave,None,Reg,Lvl,Inside,Gtl,NAmes,Artery,Norm,Duplex,2Story,-0.790370,-0.504499,-0.091314,-0.784792,Gable,CompShg,MetalSd,MetalSd,BrkFace,1.460604,TA,TA,CBlock,TA,TA,No,LwQ,0.112040,Unf,-0.287698,0.417657,0.420919,GasA,TA,Y,SBrkr,0.442698,2.202206,-0.123494,2.124523,1.086130,3.873394,0.799861,3.184712,3.874655,4.189173,TA,3.341101,Typ,-0.965196,None,Detchd,0.225300,Unf,2.991022,2.316114,TA,TA,Y,-0.735192,-0.715402,-0.352538,-0.117729,-0.257976,-0.071069,None,None,None,-0.086176,0.615801,0.890778,WD,Normal

In [220]:
Input_col[categorical_cols].nunique()

MSZoning          5
Street            2
Alley             3
LotShape          4
LandContour       4
LotConfig         5
LandSlope         3
Neighborhood     25
Condition1        9
Condition2        7
BldgType          5
HouseStyle        8
RoofStyle         6
RoofMatl          7
Exterior1st      15
Exterior2nd      16
MasVnrType        4
ExterQual         4
ExterCond         5
Foundation        6
BsmtQual          5
BsmtCond          5
BsmtExposure      5
BsmtFinType1      7
BsmtFinType2      7
Heating           6
HeatingQC         4
CentralAir        2
Electrical        5
KitchenQual       4
Functional        7
FireplaceQu       6
GarageType        7
GarageFinish      4
GarageQual        6
GarageCond        6
PavedDrive        3
PoolQC            4
Fence             5
MiscFeature       5
SaleType          9
SaleCondition     6
dtype: int64

Maping

In [221]:
Input_col['CentralAir']=Input_col['CentralAir'].map({'Y':1,'N':0})
Input_col['Street']=Input_col['Street'].map({'Pave':1,'Grvl':0})
Input_col['PavedDrive'] = Input_col['PavedDrive'].map({'Y': 3, 'P': 2, 'N': 1}).fillna(0)
Input_col['Fence']=Input_col['Fence'].map({'GdPrv':4,'MnPrv':3, 'GdWo':2, 'MnWw':1, 'None':0})
#
Val_df_Input['CentralAir']=Val_df_Input['CentralAir'].map({'Y':1,'N':0})
Val_df_Input['Street']=Val_df_Input['Street'].map({'Pave':1,'Grvl':0})
Val_df_Input['PavedDrive'] = Val_df_Input['PavedDrive'].map({'Y': 3, 'P': 2, 'N': 1}).fillna(0)
Val_df_Input['Fence']=Val_df_Input['Fence'].map({'GdPrv':4,'MnPrv':3, 'GdWo':2, 'MnWw':1, 'None':0})
#
Test_df_input['CentralAir']=Test_df_input['CentralAir'].map({'Y':1,'N':0})
Test_df_input['Street']=Test_df_input['Street'].map({'Pave':1,'Grvl':0})
Test_df_input['PavedDrive'] = Test_df_input['PavedDrive'].map({'Y': 3, 'P': 2, 'N': 1}).fillna(0)
Test_df_input['Fence']=Test_df_input['Fence'].map({'GdPrv':4,'MnPrv':3, 'GdWo':2, 'MnWw':1, 'None':0})
#make a list of all quality columns 
Qual_col=Input_col.columns[Input_col.columns.str.contains('Qual$|Cond$|QC$|Qu$')].tolist()

qual_map = {'Ex': 5, 'Gd': 4, 'TA': 3, 'Fa': 2, 'Po': 1, 'None': 0}
for col in Qual_col:
    Input_col[col]=Input_col[col].map(qual_map).fillna(0)
    Val_df_Input[col]=Val_df_Input[col].map(qual_map).fillna(0)
    Test_df_input[col]=Test_df_input[col].map(qual_map).fillna(0)

In [222]:
Not_In_Qual_Col_But_Qual=['CentralAir','Street','PavedDrive','Fence']
All_qual = list(set(Qual_col+Not_In_Qual_Col_But_Qual))

In [223]:
Hot_Encoding_Cols=list(set(categorical_cols)-set(All_qual))

In [224]:
Hot_Encoding_Cols

['BsmtExposure',
 'LandSlope',
 'GarageType',
 'LotShape',
 'Heating',
 'Alley',
 'BsmtFinType2',
 'LandContour',
 'Functional',
 'BldgType',
 'SaleType',
 'HouseStyle',
 'Condition1',
 'BsmtFinType1',
 'RoofMatl',
 'GarageFinish',
 'SaleCondition',
 'MiscFeature',
 'LotConfig',
 'Exterior1st',
 'MSZoning',
 'RoofStyle',
 'Condition2',
 'Exterior2nd',
 'Foundation',
 'Electrical',
 'Neighborhood',
 'MasVnrType']

One Hot Encodding

In [225]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoder.fit(Input_col[Hot_Encoding_Cols])

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [ ]:
encoder.categories_

In [228]:
encoder_col=list(encoder.get_feature_names_out(Hot_Encoding_Cols))
print(encoder_col)

['BsmtExposure_Av', 'BsmtExposure_Gd', 'BsmtExposure_Mn', 'BsmtExposure_No', 'BsmtExposure_None', 'LandSlope_Gtl', 'LandSlope_Mod', 'LandSlope_Sev', 'GarageType_2Types', 'GarageType_Attchd', 'GarageType_Basment', 'GarageType_BuiltIn', 'GarageType_CarPort', 'GarageType_Detchd', 'GarageType_None', 'LotShape_IR1', 'LotShape_IR2', 'LotShape_IR3', 'LotShape_Reg', 'Heating_Floor', 'Heating_GasA', 'Heating_GasW', 'Heating_Grav', 'Heating_OthW', 'Heating_Wall', 'Alley_Grvl', 'Alley_None', 'Alley_Pave', 'BsmtFinType2_ALQ', 'BsmtFinType2_BLQ', 'BsmtFinType2_GLQ', 'BsmtFinType2_LwQ', 'BsmtFinType2_None', 'BsmtFinType2_Rec', 'BsmtFinType2_Unf', 'LandContour_Bnk', 'LandContour_HLS', 'LandContour_Low', 'LandContour_Lvl', 'Functional_Maj1', 'Functional_Maj2', 'Functional_Min1', 'Functional_Min2', 'Functional_Mod', 'Functional_Sev', 'Functional_Typ', 'BldgType_1Fam', 'BldgType_2fmCon', 'BldgType_Duplex', 'BldgType_Twnhs', 'BldgType_TwnhsE', 'SaleType_COD', 'SaleType_CWD', 'SaleType_Con', 'SaleType_ConLD', 'SaleType_ConLI', 'SaleType_ConLw', 'SaleType_New', 'SaleType_Oth', 'SaleType_WD', 'HouseStyle_1.5Fin', 'HouseStyle_1.5Unf', 'HouseStyle_1Story', 'HouseStyle_2.5Fin', 'HouseStyle_2.5Unf', 'HouseStyle_2Story', 'HouseStyle_SFoyer', 'HouseStyle_SLvl', 'Condition1_Artery', 'Condition1_Feedr', 'Condition1_Norm', 'Condition1_PosA', 'Condition1_PosN', 'Condition1_RRAe', 'Condition1_RRAn', 'Condition1_RRNe', 'Condition1_RRNn', 'BsmtFinType1_ALQ', 'BsmtFinType1_BLQ', 'BsmtFinType1_GLQ', 'BsmtFinType1_LwQ', 'BsmtFinType1_None', 'BsmtFinType1_Rec', 'BsmtFinType1_Unf', 'RoofMatl_ClyTile', 'RoofMatl_CompShg', 'RoofMatl_Metal', 'RoofMatl_Roll', 'RoofMatl_Tar&Grv', 'RoofMatl_WdShake', 'RoofMatl_WdShngl', 'GarageFinish_Fin', 'GarageFinish_None', 'GarageFinish_RFn', 'GarageFinish_Unf', 'SaleCondition_Abnorml', 'SaleCondition_AdjLand', 'SaleCondition_Alloca', 'SaleCondition_Family', 'SaleCondition_Normal', 'SaleCondition_Partial', 'MiscFeature_Gar2', 'MiscFeature_None', 'MiscFeature_Othr', 'MiscFeature_Shed', 'MiscFeature_TenC', 'LotConfig_Corner', 'LotConfig_CulDSac', 'LotConfig_FR2', 'LotConfig_FR3', 'LotConfig_Inside', 'Exterior1st_AsbShng', 'Exterior1st_AsphShn', 'Exterior1st_BrkComm', 'Exterior1st_BrkFace', 'Exterior1st_CBlock', 'Exterior1st_CemntBd', 'Exterior1st_HdBoard', 'Exterior1st_ImStucc', 'Exterior1st_MetalSd', 'Exterior1st_Plywood', 'Exterior1st_Stone', 'Exterior1st_Stucco', 'Exterior1st_VinylSd', 'Exterior1st_Wd Sdng', 'Exterior1st_WdShing', 'MSZoning_C (all)', 'MSZoning_FV', 'MSZoning_RH', 'MSZoning_RL', 'MSZoning_RM', 'RoofStyle_Flat', 'RoofStyle_Gable', 'RoofStyle_Gambrel', 'RoofStyle_Hip', 'RoofStyle_Mansard', 'RoofStyle_Shed', 'Condition2_Artery', 'Condition2_Feedr', 'Condition2_Norm', 'Condition2_PosN', 'Condition2_RRAe', 'Condition2_RRAn', 'Condition2_RRNn', 'Exterior2nd_AsbShng', 'Exterior2nd_AsphShn', 'Exterior2nd_Brk Cmn', 'Exterior2nd_BrkFace', 'Exterior2nd_CBlock', 'Exterior2nd_CmentBd', 'Exterior2nd_HdBoard', 'Exterior2nd_ImStucc', 'Exterior2nd_MetalSd', 'Exterior2nd_Other', 'Exterior2nd_Plywood', 'Exterior2nd_Stone', 'Exterior2nd_Stucco', 'Exterior2nd_VinylSd', 'Exterior2nd_Wd Sdng', 'Exterior2nd_Wd Shng', 'Foundation_BrkTil', 'Foundation_CBlock', 'Foundation_PConc', 'Foundation_Slab', 'Foundation_Stone', 'Foundation_Wood', 'Electrical_FuseA', 'Electrical_FuseF', 'Electrical_FuseP', 'Electrical_Mix', 'Electrical_SBrkr', 'Neighborhood_Blmngtn', 'Neighborhood_Blueste', 'Neighborhood_BrDale', 'Neighborhood_BrkSide', 'Neighborhood_ClearCr', 'Neighborhood_CollgCr', 'Neighborhood_Crawfor', 'Neighborhood_Edwards', 'Neighborhood_Gilbert', 'Neighborhood_IDOTRR', 'Neighborhood_MeadowV', 'Neighborhood_Mitchel', 'Neighborhood_NAmes', 'Neighborhood_NPkVill', 'Neighborhood_NWAmes', 'Neighborhood_NoRidge', 'Neighborhood_NridgHt', 'Neighborhood_OldTown', 'Neighborhood_SWISU', 'Neighborhood_Sawyer', 'Neighborhood_SawyerW', 'Neighborhood_Somerst', 'Neighborhood_StoneBr', 'Neighborhood_Timber', 'Neighborhood_Veenker', 'MasVnrType_BrkCmn', 'MasVnrType_BrkFace', 'MasVnrType_None', 'MasVnrType_Stone']

In [231]:
Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
Val_df_Input[encoder_col]=encoder.transform(Val_df_Input[Hot_Encoding_Cols])
Test_df_input[encoder_col]=encoder.transform(Test_df_input[Hot_Encoding_Cols])

/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])
/tmp/ipykernel_33744/4214286970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Input_col[encoder_col]=encoder.transform(Input_col[Hot_Encoding_Cols])

In [232]:
Input_col

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,BsmtExposure_Av,BsmtExposure_Gd,BsmtExposure_Mn,BsmtExposure_No,BsmtExposure_None,LandSlope_Gtl,LandSlope_Mod,LandSlope_Sev,GarageType_2Types,GarageType_Attchd,GarageType_Basment,GarageType_BuiltIn,GarageType_CarPort,GarageType_Detchd,GarageType_None,LotShape_IR1,LotShape_IR2,LotShape_IR3,LotShape_Reg,Heating_Floor,Heating_GasA,Heating_GasW,Heating_Grav,Heating_OthW,Heating_Wall,Alley_Grvl,Alley_None,Alley_Pave,BsmtFinType2_ALQ,BsmtFinType2_BLQ,BsmtFinType2_GLQ,BsmtFinType2_LwQ,BsmtFinType2_None,BsmtFinType2_Rec,BsmtFinType2_Unf,LandContour_Bnk,LandContour_HLS,LandContour_Low,LandContour_Lvl,Functional_Maj1,Functional_Maj2,Functional_Min1,Functional_Min2,Functional_Mod,Functional_Sev,Functional_Typ,BldgType_1Fam,BldgType_2fmCon,BldgType_Duplex,BldgType_Twnhs,BldgType_TwnhsE,SaleType_COD,SaleType_CWD,SaleType_Con,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,HouseStyle_1.5Fin,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,HouseStyle_SFoyer,HouseStyle_SLvl,Condition1_Artery,Condition1_Feedr,Condition1_Norm,Condition1_PosA,Condition1_PosN,Condition1_RRAe,Condition1_RRAn,Condition1_RRNe,Condition1_RRNn,BsmtFinType1_ALQ,BsmtFinType1_BLQ,BsmtFinType1_GLQ,BsmtFinType1_LwQ,BsmtFinType1_None,BsmtFinType1_Rec,BsmtFinType1_Unf,RoofMatl_ClyTile,RoofMatl_CompShg,RoofMatl_Metal,RoofMatl_Roll,RoofMatl_Tar&Grv,RoofMatl_WdShake,RoofMatl_WdShngl,GarageFinish_Fin,GarageFinish_None,GarageFinish_RFn,GarageFinish_Unf,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,MiscFeature_Gar2,MiscFeature_None,MiscFeature_Othr,MiscFeature_Shed,MiscFeature_TenC,LotConfig_Corner,LotConfig_CulDSac,LotConfig_FR2,LotConfig_FR3,LotConfig_Inside,Exterior1st_AsbShng,Exterior1st_AsphShn,Exterior1st_BrkComm,Exterior1st_BrkFace,Exterior1st_CBlock,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing,MSZoning_C (all),MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,RoofStyle_Flat,RoofStyle_Gable,RoofStyle_Gambrel,RoofStyle_Hip,RoofStyle_Mansard,RoofStyle_Shed,Condition2_Artery,Condition2_Feedr,Condition2_Norm,Condition2_PosN,Condition2_RRAe,Condition2_RRAn,Condition2_RRNn,Exterior2nd_AsbShng,Exterior2nd_AsphShn,Exterior2nd_Brk Cmn,Exterior2nd_BrkFace,Exterior2nd_CBlock,Exterior2nd_CmentBd,Exterior2nd_HdBoard,Exterior2nd_ImStucc,Exterior2nd_MetalSd,Exterior2nd_Other,Exterior2nd_Plywood,Exterior2nd_Stone,Exterior2nd_Stucco,Exterior2nd_VinylSd,Exterior2nd_Wd Sdng,Exterior2nd_Wd Shng,Foundation_BrkTil,Foundation_CBlock,Foundation_PConc,Foundation_Slab,Foundation_Stone,Foundation_Wood,Electrical_FuseA,Electrical_FuseF,Electrical_FuseP,Electrical_Mix,Electrical_SBrkr,Neighborhood_Blmngtn,Neighborhood_Blueste,Neighborhood_BrDale,Neighborhood_BrkSide,Neighborhood_ClearCr,Neighborhood_CollgCr,Neighborhood_Crawfor,Neighborhood_Edwards,Neighborhood_Gilbert,Neighborhood_IDOTRR,Neighborhood_MeadowV,Neighborhood_Mitchel,Neighborhood_NAmes,Neighborhood_NPkVill,Neighborhood_NWAmes,Neighborhood_NoRidge,Neighborhood_NridgHt,Neighborhood_OldTown,Neighborhood_SWISU,Neighborhood_Sawyer,Neighborhood_SawyerW,Neighborhood_Somerst,Neighborhood_StoneBr,Neighborhood_Timber,Neighborhood_Veenker,MasVnrType_BrkCmn,MasVnrType_BrkFace,MasVnrType_None,MasVnrType_Stone
609,-0.871658,RL,-0.412306,-0.252659,1,None,Reg,Lvl,Inside,Gtl,Sawyer,Feedr,Norm,1Fam,1Story,0.0,0.0,-0.358283,-1.174415,Gable,CompShg,VinylSd,VinylSd,BrkCmn,0.490392,3,2,CBlock,3,3,Mn,Rec,0.979082,Unf,-0.287698,-0.987686,-0.067266,GasA,4,1,SBrkr,-0.349456,-0.788740,-0.123494,-0.917962,1.086130,-0.243189,-1.028393,-0.766158,0.174249,-0.214926,3,-0.927155,Typ,-0.965196,0,Attchd,0.207936,Unf,-1.010712,-0.976445,3,3,3,-0.230072,-0.715402,0.286313,-0.117729,-0.257976,-0.071069,0,0,None,-0.086176,-0.878757,-0.614908,WD,Normal,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1361,-0.871658,RL,2.391941,0.498726,1,None,IR1,Low,Inside,Mod,StoneBr,Norm,Norm,1Fam,1Story,0.0,0.0,1.110048,0.968512,Hip,CompShg,VinylSd,VinylSd,Stone,-0.479820,4,3,PConc,5,3,Av,ALQ,1.777277,Unf,-0.287698,-0.693965,1.049542,GasA,5,1,SBrkr,0.934911,-0.788740,-0.123494,0.031749,1.086130,-0.243189,0.799861,-0.766158,0.174249,-0.214926,4,0.292346,Typ,0.568612,4,Attchd,0.303436,Fin,0.323199,-0.189397,3,3,3,0.590748,-0.161216,-0.352538,-0.117729,-0.257976,-0.071069,0,0,None,-0.086176,-0.131478,0.890778,WD,Normal,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1076,-0.165219,RL,-0.456818,0.008656,1,Grvl,Reg,Lvl,Inside,Gtl,OldTown,Norm,Norm,1Fam,1.5Fin,0.0,0.0,-1.192562,0.189266,Gable,CompShg,Wd Sdng,Wd Sdng,None,-0.568021,3,3,CBlock,2,3,No,ALQ,0.383125,Unf,-0.287698,-0.888273,-0.586660,GasA,4,1,SBrkr,-0.177694,0.065157,-0.123494,-0.089572,-0.838908,3.873394,0.799861,-0.766158,0.174249,-0.214926,4,0.292346,Min1,0.568612,3,Attchd,0.184062,Unf,0.323199,0.443966,3,3,3,2.705938,-0.392127,-0.352538,-0.117729,-0.257976,-0.071069,0,0,Shed,0.831121,-0.878757,-1.367751,WD,Normal,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1138,-0.871658,RL,-0.011700,-0.081071,1,None,IR1,Lvl,Inside,Mod,Mitchel,Norm,Norm,1Fam,1Story,0.0,0.0,0.175656,-0.395169,Gable,CompShg,Plywood,ImStucc,None,-0.568021,3,3,PConc,3,3,Gd,ALQ,2.407657,Unf,-0.287698,-1.272370,1.132020,GasA,3,1,SBrkr,1.029764,-0.788740,-0.123494,0.101887,1.086130,-0.243189,0.799861,-0.766158,-1.059220,-0.214926,4,-0.927155,Typ,2.102421,3,Attchd,0.242663,RFn,0.323199,1.133215,3,3,3,1.348428,-0.222792,-0.352538,-0.117729,-0.257976,-0.071069,0,0,None,-0.086176,-0.505117,0.890778,WD,Normal,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1159,0.070261,RL,0.255372,-0.145005,1,None,Reg,Lvl,Inside,Gtl,NWAmes,Norm,Norm,1Fam,2Story,0.0,0.0,0.075542,-0.541277,Hip,CompShg,HdBoard,HdBoard,BrkFace,0.920372,4,3,CBlock,3,3,No,ALQ,-0.012745,Unf,-0.287698,-0.235308,-0.352598,GasA,3,1,SBrkr,-0.569926,1.364464,-0.123494,0.687636,-0.838908,-0.243189,0.799861,1.209277,1.407718,-0.214926,4,0.902097,Typ,0.568612,3,Attchd,0.236152,RFn,0.323199,0.322882,4,3,3,-0.735192,0.346788,-0.352538,-0.117729,-0.257976,-0.071069,0,0,None,-0.086176,0.242162,0.137935,WD,Normal,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1016,-0.871658,RL,0.121836,0.107713,1,None,Reg,Lvl,Inside,Gtl,CollgCr,Norm,Norm,1Fam,1Story,0.0,0.0,0.809708,0.530186,Hip,CompShg,VinylSd,VinylSd,BrkFace,0.512442,4,3,PConc,4,3,Gd,GLQ,0.520819,Unf,-0.287698,0.566777,0.991584,GasA,5,1,SBrkr,0.868257,-0.788740,-0.123494,-0.017538,1.086130,-0.243189,0.799861,-0.766158,0.174249,-0.214926,4,-0.317405,Typ,0.568612,3,Attchd,0.283902,Fin,0.323199,0.034143,3,3,3,0.172446,0.300606,-0.352538,-0.117729,-0.257976,-0.071069,0,0,None,-0.086176,-0.131478,0.890778,WD,Normal,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
165,3.131496,RL,-0.367794,-0.054820,1,None,Reg,Lvl,Inside,Gtl,Edwards,Norm,Norm,2fmCon,1.5Fin,0.0,0.0,-1.059077,0.676294,Gable,CompShg,Wd Sdng,Wd Sdng,None,-0.568021,3,4,BrkTil,3,3,No,ALQ,-0.208528,Rec,0.794789,-1.019318,-0.925491,GasA,4,1,SBrkr,-0.916013,0.473642,-0.123494,-0.299987,1.086130,-0.243189,0.799861,-0.766158,1.407718,4.189173,3,-0.317405,Typ,-0.965196,0,None,-4.048289,None,-2.344623,-2.191944,0,0,3,0.369758,-0.715402,-0.352538,-0.117729,-0.257976,-0.071069,0,0,None,-0.086176,0.989441,0.137935,WD,Normal,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7,0.070261,RL,-0.011700,-0.029576,1,None,IR1,Lvl,Corner,Gtl,NWAmes,PosN,Norm,1Fam,2Story,0.0,0.0,0.042171,-0.589980,Gable,CompShg,HdBoard,HdBoard,Stone,0.754995,3,3,CBlock,4,3,Mn,ALQ,0.884417,BLQ,-0.096319,-0.784341,0.106608,GasA,5,1,SBrkr,-0.149495,1.479855,-0.123494,1.093301,1.086130,-0.243189,0.799861,1.209277,0.174249,-0.214926,3,0.292346,Typ,2.102421,3,Attchd,0.233982,RFn,0.323199,0.062085,3,3,3,1.119545,2.424987,3.382284,-0.117729,-0.257976,-0.071069,0,0,Shed,0.555932,1.736720,0.890778,WD,Normal,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
219,1.483139,RL,-1.213520,-0.703856,1,None,Reg,Lvl,Inside,Gtl,Blmngtn,Norm,Norm,TwnhsE,1Story,0.0,0.0,1.110048,1.017214,Gable,CompShg,VinylSd,VinylSd,BrkFace,-0.479820,4,3,PConc,4,3,Av,GLQ,-0.929270,Unf,-0.287698,1.511204,0.420919,GasA,5,1,SBrkr,0.211974,-0.788740,-0.123494,-0.502819,-0.838908,-0.243189,0.799861,-0.766158,-1.059220,-0.214926,4,-0.927155,Typ,-0.965196,0,Attchd,0.303436,Fin,0.323199,-0.152141,3,3,3,0.117198,-0.715402,-0.352538,-0.117729,-0.257976,-0.071069,0,0,None,-0.086176,-1.252396,-1.367751,New,Partial,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1350,0.776700,RL,0.923049,0.085761,1,None,Reg,Lvl,Inside,Gtl,NAmes,Artery,Norm,Duplex,2Story,0.0,0.0,-0.091314,-0.784792,Gable,CompShg,MetalSd,MetalSd,BrkFace,1.460604,3,3,CBlock,3,3,No,LwQ,0.112040,Unf,-0.287698,0.417657,0.420919,GasA,3,1,SBrkr,0.442698,2.202206,-0.123494,2.124523,1.086130,3.873394,0.799861,3.184712,3.874655,4.189173,3,3.341101,Typ,-0.965196,0,Detchd,0.225300,Unf,2.991022,2.316114,3,3,3,-0.735192,-0.715402,-0.352538,-0.117729,-0.257976,-0.071069,0,0,None,-0.086176,0.615801,0.890778,WD,Normal,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [239]:
raw_cat_cols = [
    'MSZoning', 'Alley', 'LotShape', 'LandContour', 'LotConfig', 'LandSlope', 
    'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 
    'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 
    'Foundation', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 
    'Functional', 'GarageType', 'GarageFinish', 'MiscFeature', 'SaleType', 
    'SaleCondition','Electrical'
]
Input_col     = Input_col.drop(columns=[col for col in raw_cat_cols if col in Input_col.columns])
Val_df_Input  = Val_df_Input.drop(columns=[col for col in raw_cat_cols if col in Val_df_Input.columns])
Test_df_input = Test_df_input.drop(columns=[col for col in raw_cat_cols if col in Test_df_input.columns])

In [240]:
Input_col

,MSSubClass,LotFrontage,LotArea,Street,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,ExterQual,ExterCond,BsmtQual,BsmtCond,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,HeatingQC,CentralAir,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Fireplaces,FireplaceQu,GarageYrBlt,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscVal,MoSold,YrSold,BsmtExposure_Av,BsmtExposure_Gd,BsmtExposure_Mn,BsmtExposure_No,BsmtExposure_None,LandSlope_Gtl,LandSlope_Mod,LandSlope_Sev,GarageType_2Types,GarageType_Attchd,GarageType_Basment,GarageType_BuiltIn,GarageType_CarPort,GarageType_Detchd,GarageType_None,LotShape_IR1,LotShape_IR2,LotShape_IR3,LotShape_Reg,Heating_Floor,Heating_GasA,Heating_GasW,Heating_Grav,Heating_OthW,Heating_Wall,Alley_Grvl,Alley_None,Alley_Pave,BsmtFinType2_ALQ,BsmtFinType2_BLQ,BsmtFinType2_GLQ,BsmtFinType2_LwQ,BsmtFinType2_None,BsmtFinType2_Rec,BsmtFinType2_Unf,LandContour_Bnk,LandContour_HLS,LandContour_Low,LandContour_Lvl,Functional_Maj1,Functional_Maj2,Functional_Min1,Functional_Min2,Functional_Mod,Functional_Sev,Functional_Typ,BldgType_1Fam,BldgType_2fmCon,BldgType_Duplex,BldgType_Twnhs,BldgType_TwnhsE,SaleType_COD,SaleType_CWD,SaleType_Con,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,HouseStyle_1.5Fin,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,HouseStyle_SFoyer,HouseStyle_SLvl,Condition1_Artery,Condition1_Feedr,Condition1_Norm,Condition1_PosA,Condition1_PosN,Condition1_RRAe,Condition1_RRAn,Condition1_RRNe,Condition1_RRNn,BsmtFinType1_ALQ,BsmtFinType1_BLQ,BsmtFinType1_GLQ,BsmtFinType1_LwQ,BsmtFinType1_None,BsmtFinType1_Rec,BsmtFinType1_Unf,RoofMatl_ClyTile,RoofMatl_CompShg,RoofMatl_Metal,RoofMatl_Roll,RoofMatl_Tar&Grv,RoofMatl_WdShake,RoofMatl_WdShngl,GarageFinish_Fin,GarageFinish_None,GarageFinish_RFn,GarageFinish_Unf,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,MiscFeature_Gar2,MiscFeature_None,MiscFeature_Othr,MiscFeature_Shed,MiscFeature_TenC,LotConfig_Corner,LotConfig_CulDSac,LotConfig_FR2,LotConfig_FR3,LotConfig_Inside,Exterior1st_AsbShng,Exterior1st_AsphShn,Exterior1st_BrkComm,Exterior1st_BrkFace,Exterior1st_CBlock,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing,MSZoning_C (all),MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,RoofStyle_Flat,RoofStyle_Gable,RoofStyle_Gambrel,RoofStyle_Hip,RoofStyle_Mansard,RoofStyle_Shed,Condition2_Artery,Condition2_Feedr,Condition2_Norm,Condition2_PosN,Condition2_RRAe,Condition2_RRAn,Condition2_RRNn,Exterior2nd_AsbShng,Exterior2nd_AsphShn,Exterior2nd_Brk Cmn,Exterior2nd_BrkFace,Exterior2nd_CBlock,Exterior2nd_CmentBd,Exterior2nd_HdBoard,Exterior2nd_ImStucc,Exterior2nd_MetalSd,Exterior2nd_Other,Exterior2nd_Plywood,Exterior2nd_Stone,Exterior2nd_Stucco,Exterior2nd_VinylSd,Exterior2nd_Wd Sdng,Exterior2nd_Wd Shng,Foundation_BrkTil,Foundation_CBlock,Foundation_PConc,Foundation_Slab,Foundation_Stone,Foundation_Wood,Electrical_FuseA,Electrical_FuseF,Electrical_FuseP,Electrical_Mix,Electrical_SBrkr,Neighborhood_Blmngtn,Neighborhood_Blueste,Neighborhood_BrDale,Neighborhood_BrkSide,Neighborhood_ClearCr,Neighborhood_CollgCr,Neighborhood_Crawfor,Neighborhood_Edwards,Neighborhood_Gilbert,Neighborhood_IDOTRR,Neighborhood_MeadowV,Neighborhood_Mitchel,Neighborhood_NAmes,Neighborhood_NPkVill,Neighborhood_NWAmes,Neighborhood_NoRidge,Neighborhood_NridgHt,Neighborhood_OldTown,Neighborhood_SWISU,Neighborhood_Sawyer,Neighborhood_SawyerW,Neighborhood_Somerst,Neighborhood_StoneBr,Neighborhood_Timber,Neighborhood_Veenker,MasVnrType_BrkCmn,MasVnrType_BrkFace,MasVnrType_None,MasVnrType_Stone
609,-0.871658,-0.412306,-0.252659,1,0.0,0.0,-0.358283,-1.174415,0.490392,3,2,3,3,0.979082,-0.287698,-0.987686,-0.067266,4,1,-0.349456,-0.788740,-0.123494,-0.917962,1.086130,-0.243189,-1.028393,-0.766158,0.174249,-0.214926,3,-0.927155,-0.965196,0,0.207936,-1.010712,-0.976445,3,3,3,-0.230072,-0.715402,0.286313,-0.117729,-0.257976,-0.071069,0,0,-0.086176,-0.878757,-0.614908,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1361,-0.871658,2.391941,0.498726,1,0.0,0.0,1.110048,0.968512,-0.479820,4,3,5,3,1.777277,-0.287698,-0.693965,1.049542,5,1,0.934911,-0.788740,-0.123494,0.031749,1.086130,-0.243189,0.799861,-0.766158,0.174249,-0.214926,4,0.292346,0.568612,4,0.303436,0.323199,-0.189397,3,3,3,0.590748,-0.161216,-0.352538,-0.117729,-0.257976,-0.071069,0,0,-0.086176,-0.131478,0.890778,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1076,-0.165219,-0.456818,0.008656,1,0.0,0.0,-1.192562,0.189266,-0.568021,3,3,2,3,0.383125,-0.287698,-0.888273,-0.586660,4,1,-0.177694,0.065157,-0.123494,-0.089572,-0.838908,3.873394,0.799861,-0.766158,0.174249,-0.214926,4,0.292346,0.568612,3,0.184062,0.323199,0.443966,3,3,3,2.705938,-0.392127,-0.352538,-0.117729,-0.257976,-0.071069,0,0,0.831121,-0.878757,-1.367751,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1138,-0.871658,-0.011700,-0.081071,1,0.0,0.0,0.175656,-0.395169,-0.568021,3,3,3,3,2.407657,-0.287698,-1.272370,1.132020,3,1,1.029764,-0.788740,-0.123494,0.101887,1.086130,-0.243189,0.799861,-0.766158,-1.059220,-0.214926,4,-0.927155,2.102421,3,0.242663,0.323199,1.133215,3,3,3,1.348428,-0.222792,-0.352538,-0.117729,-0.257976,-0.071069,0,0,-0.086176,-0.505117,0.890778,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1159,0.070261,0.255372,-0.145005,1,0.0,0.0,0.075542,-0.541277,0.920372,4,3,3,3,-0.012745,-0.287698,-0.235308,-0.352598,3,1,-0.569926,1.364464,-0.123494,0.687636,-0.838908,-0.243189,0.799861,1.209277,1.407718,-0.214926,4,0.902097,0.568612,3,0.236152,0.323199,0.322882,4,3,3,-0.735192,0.346788,-0.352538,-0.117729,-0.257976,-0.071069,0,0,-0.086176,0.242162,0.137935,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1016,-0.871658,0.121836,0.107713,1,0.0,0.0,0.809708,0.530186,0.512442,4,3,4,3,0.520819,-0.287698,0.566777,0.991584,5,1,0.868257,-0.788740,-0.123494,-0.017538,1.086130,-0.243189,0.799861,-0.766158,0.174249,-0.214926,4,-0.317405,0.568612,3,0.283902,0.323199,0.034143,3,3,3,0.172446,0.300606,-0.352538,-0.117729,-0.257976,-0.071069,0,0,-0.086176,-0.131478,0.890778,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
165,3.131496,-0.367794,-0.054820,1,0.0,0.0,-1.059077,0.676294,-0.568021,3,4,3,3,-0.208528,0.794789,-1.019318,-0.925491,4,1,-0.916013,0.473642,-0.123494,-0.299987,1.086130,-0.243189,0.799861,-0.766158,1.407718,4.189173,3,-0.317405,-0.965196,0,-4.048289,-2.344623,-2.191944,0,0,3,0.369758,-0.715402,-0.352538,-0.117729,-0.257976,-0.071069,0,0,-0.086176,0.989441,0.137935,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7,0.070261,-0.011700,-0.029576,1,0.0,0.0,0.042171,-0.589980,0.754995,3,3,4,3,0.884417,-0.096319,-0.784341,0.106608,5,1,-0.149495,1.479855,-0.123494,1.093301,1.086130,-0.243189,0.799861,1.209277,0.174249,-0.214926,3,0.292346,2.102421,3,0.233982,0.323199,0.062085,3,3,3,1.119545,2.424987,3.382284,-0.117729,-0.257976,-0.071069,0,0,0.555932,1.736720,0.890778,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
219,1.483139,-1.213520,-0.703856,1,0.0,0.0,1.110048,1.017214,-0.479820,4,3,4,3,-0.929270,-0.287698,1.511204,0.420919,5,1,0.211974,-0.788740,-0.123494,-0.502819,-0.838908,-0.243189,0.799861,-0.766158,-1.059220,-0.214926,4,-0.927155,-0.965196,0,0.303436,0.323199,-0.152141,3,3,3,0.117198,-0.715402,-0.352538,-0.117729,-0.257976,-0.071069,0,0,-0.086176,-1.252396,-1.367751,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1350,0.776700,0.923049,0.085761,1,0.0,0.0,-0.091314,-0.784792,1.460604,3,3,3,3,0.112040,-0.287698,0.417657,0.420919,3,1,0.442698,2.202206,-0.123494,2.124523,1.086130,3.873394,0.799861,3.184712,3.874655,4.189173,3,3.341101,-0.965196,0,0.225300,2.991022,2.316114,3,3,3,-0.735192,-0.715402,-0.352538,-0.117729,-0.257976,-0.071069,0,0,-0.086176,0.615801,0.890778,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [250]:
from sklearn.linear_model import Ridge

In [251]:
model = Ridge(alpha=10.0)
model.fit(Input_col, Target_col)

Ridge(alpha=10.0)

In [252]:
Val_df_Input['GarageYrBlt']  = Val_df_Input['GarageYrBlt'].fillna(Val_df_Input['YearBuilt'])

In [253]:
predictio_val=model.predict(Val_df_Input)

In [ ]:
Prediction

array([197846.09996196, 165326.89229773, 291692.27274243, 157129.24898788,
       292961.94232667,  70188.5212314 , 153198.20807819, 133608.4308488 ,
        97695.11010732, 211788.5159336 , 123595.62367878, 346748.2884965 ,
       184392.75848592, 133628.93598044, 154116.14648003, 281232.4625736 ,
       186710.54901417, 301751.84303042, 419123.1076851 , 134241.8863375 ,
       199007.79417581, 169307.15365172, 140568.10448366, 174833.43555616,
       140948.94926985, 119527.14004855, 278033.04929702, 164035.3204047 ,
       128892.69862155, 187612.02292934, 127511.66521973, 200666.49991959,
       133905.06282141, 150851.39045227, 156000.57829946, 138236.55066451,
       171224.293435  , 261224.55200006, 206164.03403522, 353016.98777345,
        74995.81506663, 114247.19814089, 132749.87864853, 172153.13037219,
        94358.69060154, 140496.69810485, 254921.92124067, 303531.4682535 ,
       190439.64869638, 193606.80933428, 231904.60058253, 133087.64320865,
       139104.62733851, 143706.8109321 , 170014.54129103, 212187.15492884,
        46065.60780516, 222691.59421884, 119625.67537993,  67891.65046652,
       131667.95565549, 180899.67250344, 228123.03002526, 123788.75039961,
       107870.64097943, 330500.07700647, 233175.84413146, 139074.81923635,
       120672.22124403, 214800.91647623, 266429.8107713 , 112534.63741271,
       201950.19151368, 156909.81460428, 332955.29445338, 124083.17430602,
       253920.83165643, 200103.02677725, 153507.60295795, 186755.86803398,
       175854.47570233, 139036.62177255, 128960.36937544, 161507.07661789,
       234899.08146667, 249919.12936914, 352281.92632358, 204828.69496915,
       130117.30954164, 144156.33718703, 119398.83173289, 185414.36361266,
       179147.79978726, 130247.03440746, 212498.6690987 ,   4083.84547666,
       149276.90933573, 155179.47249343,  70992.11868881, 255576.99844796,
       185883.27606102,  99737.56890915, 216223.43806111, 204814.85977834,
       120184.86939563, 153949.17934733, 187700.67877387, 185183.33892719,
       207159.56439287, 337088.34571568, 153218.35858874, 182689.11033621,
       223336.01083714, 128209.13402346, 292615.19047219,  83957.65300445,
       117212.99492733, 137650.10885829, 162808.52436099, 284607.14935038,
       112990.09134922, 285203.03692959, 169160.46017298, 180828.51762475,
       144087.66247892, 136531.53311852, 135574.2469862 , 190948.96127686,
       187158.45489212, 145039.0655866 , 123013.9179825 ,  95060.84743733,
       188695.08171114, 172407.27658861, 310747.43716022, 301696.18687933,
       235202.46944064, 139255.2215018 ,  87295.92575994, 105950.39647409,
        78780.30383318, 177581.93226681, 306922.66845139, 234239.36542483,
       123869.70025451, 144894.85880542, 147744.68188919, 216353.19673366,
       140261.12203716, 186481.35254124, 139578.62294354, 181431.09191894,
       137103.17211373, 230464.69647075, 205317.67150333, 168438.84348492,
       120105.57787558, 198351.65956949, 143629.92432411, 191960.42568796,
        61893.02221796, 125723.8901731 , 159524.80378236, 157404.5488531 ,
        99255.97837292, 154012.53799105, 185339.47608789, 253603.98480359,
       250759.25781029, 180779.49082677, 205391.49661546, 408607.60488532,
       136114.37377767, 358659.30901115, 269123.18179093, 264096.26044256,
       244748.06242654, 303103.05713485, 279806.1330817 , 115356.8848129 ,
        91969.16971314, 207041.22432686, 193638.62542998, 289024.81760271,
       355320.6198088 , 159766.25147669, 159114.20116105, 140457.17694504,
       161496.08838014, 332961.69071978, 209465.18549538, 126836.94546648,
       183494.6761105 , 143205.84780052, 224360.91601011, 145269.26548568,
       331929.19042973, 120095.32560353, 153517.91015208, 237713.72353728,
       139002.17716736, 112574.53836185, 198190.46762301, 183327.77529006,
       202856.8069634 , 141714.93051195, 292131.92257977, 179182.43756334,
       137229.41227896, 137031.43779376, 195981.66970026, 267800.63033537,
       203354.28916832, 124465.82547295, 217595.63167338, 304157.50277011,
       307292.0335057 , 273972.14034943, 116401.54507782, 113084.15331945,
       191307.70602418, 116093.51379527, 225446.60786522, 185469.8202124 ,
        93265.23313781, 137588.18663737, 121638.39560748, 154973.26369386,
       268550.48528025, 172012.27201234, 208651.19944123, 118463.59720084,
       207287.7100378 , 168259.50815274, 231355.27860632,  63311.91192252,
       211261.85651174, 321189.94987733, 139829.89879287, 181674.76110903,
        27555.78879598, 193728.25262581, 133036.99038523, 292877.2923391 ,
       270064.09630685, 207289.30902557, 118173.41326987, 214335.69119785,
       202689.57986182, 148269.92674215, 176609.82031291, 128825.69168444,
        97791.80372218, 133099.88638489, 199356.58076707, 123171.88763467,
       280404.58154389,  79978.39533348, 257016.5627949 , 156088.42007353,
       327549.35841017, 201214.41077229, 136811.39722319, 106766.80023538,
       155451.45584834, 167236.78463651, 121253.0661993 , 197020.07484671,
       241019.60495701, 136899.31648242, 270865.06544541, 229375.62908865,
        95892.22697073, 140537.44537102, 132731.69461778, 221310.02671619,
       210677.46947016, 208680.5167098 , 223235.57328115, 157086.45339924,
       136117.13037092, 228098.74490476, 164071.10416437, 137824.00647019,
       301633.29265955, 112988.1719243 , 155798.48315728, 127461.35638802,
       208422.55750934, 166839.41408995, 321745.67665468, 139364.4410825 ])

In [255]:
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# 1. Generate predictions on validation set
val_preds = model.predict(Val_df_Input)

# Safety clip: Ensure no price is below 0
val_preds = np.maximum(0, val_preds)

# 2. Calculate key metrics
rmse = np.sqrt(mean_squared_error(Val_Target, val_preds))
mae  = mean_absolute_error(Val_Target, val_preds)
r2   = r2_score(Val_Target, val_preds)

print(f"Validation RMSE: ${rmse:,.2f}")
print(f"Validation MAE:  ${mae:,.2f}")
print(f"Validation R²:   {r2:.4f}")

Validation RMSE: $29,048.71
Validation MAE:  $20,586.80
Validation R²:   0.8366

In [261]:

Test_df_input['GarageYrBlt']  = Test_df_input['GarageYrBlt'].fillna(Test_df_input['YearBuilt'])

In [ ]:
missing_in_test = Test_df_input.isna().sum()
missing_in_test = missing_in_test[missing_in_test > 0]

print("Columns with missing values in Test set:")
print(missing_in_test)

Columns with missing values in Test set:
BsmtFinSF1      1
BsmtFinSF2      1
BsmtUnfSF       1
TotalBsmtSF     1
BsmtFullBath    2
BsmtHalfBath    2
GarageCars      1
GarageArea      1
dtype: int64

In [264]:
# List of basement and garage features missing in the test set
zero_fill_cols = [
    'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 
    'BsmtFullBath', 'BsmtHalfBath', 'GarageCars', 'GarageArea'
]

# Fill missing values with 0
Test_df_input[zero_fill_cols] = Test_df_input[zero_fill_cols].fillna(0)

# Verify no NaNs remain in Test_df_input
print("Total NaNs left in Test DF:", Test_df_input.isna().sum().sum())

Total NaNs left in Test DF: 0